kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jld-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld-nginx
    spec:
      containers:
      - name: jld-nginx
        image: "lsstsqre/jld-nginx"
        imagePullPolicy: "Always"
        env:
          - name: ENABLE_SSL
            value: 'true'
          - name: ENABLE_BASIC_AUTH
            value: 'false'
          - name: HOSTNAME
            value: 'FIXME'
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: tls
      
