# TLS secrets for nginx
# see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  # Each secret value must be base64 encoded.
  # e.g. `base64 root_chain.pem | tr -d '\n'`
  root_chain.pem: '{{ROOT_CHAIN_PEM}}'
  dhparam.pem: '{{DHPARAM_PEM}}'
  tls.crt: '{{TLS_CRT}}'
  tls.key: '{{TLS_KEY}}'
