# TLS secrets for nginx
# see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  # Each secret value must be base64 encoded.
  # e.g. `echo -n hello | base64 | pbcopy`
  root_chain.pem: 'FIXME'
  dhparam.pem: 'FIXME'
  tls.crt: 'FIXME'
  tls.key: 'FIXME'

  
