apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jld-keepalive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld-keepalive
    spec:
      containers:
        - name: "jld-keepalive"
          imagePullPolicy: "Always"
          image: "lsstsqre/nfsclienttest"
          # Use this for manual testing.
          #securityContext:
          #  privileged: true
          volumeMounts:
            - name: jld-fileserver-home
              mountPath: /home
            - name: jld-fileserver-scratch
              mountPath: /scratch
            - name: jld-fileserver-project
              mountPath: /project
            - name: jld-fileserver-datasets
              mountPath: /datasets
            - name: jld-fileserver-software
              mountPath: /software
      volumes:
        - name: jld-fileserver-home
          persistentVolumeClaim:
             claimName: jld-fileserver-home
        - name: jld-fileserver-scratch
          persistentVolumeClaim:
             claimName: jld-fileserver-scratch
        - name: jld-fileserver-project
          persistentVolumeClaim:
             claimName: jld-fileserver-project
        - name: jld-fileserver-datasets
          persistentVolumeClaim:
             claimName: jld-fileserver-datasets
        - name: jld-fileserver-software
          persistentVolumeClaim:
             claimName: jld-fileserver-software
