apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prepuller
spec:
  template:
    metadata:
      labels:
        name: prepuller
    spec:
      containers:
        - name: prepuller
          imagePullPolicy: "Always"
          image: "lsstsqre/prepuller"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: /var/run
            - name: dockerbin
              mountPath: /usr/bin/docker
            - name: dockerlib
              mountPath: /var/lib/docker
            - name: libapparmor
              mountPath: /usr/lib64/libapparmor.so
            - name: libapparmor1
              mountPath: /usr/lib64/libapparmor.so.1
            - name: libapparmor130
              mountPath: /usr/lib64/libapparmor.so.1.3.0
            - name: libseccomp
              mountPath: /usr/lib64/libseccomp.so
            - name: libseccomp2
              mountPath: /usr/lib64/libseccomp.so.2
            - name: libseccomp231
              mountPath: /usr/lib64/libseccomp.so.2.3.1
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
        - name: dockerbin
          hostPath:
            path: /usr/bin/docker
        - name: dockerlib
          hostPath:
            path: /var/lib/docker
        - name: libapparmor
          hostPath:
            path: /usr/lib64/libapparmor.so
        - name: libapparmor1
          hostPath:
            path: /usr/lib64/libapparmor.so.1
        - name: libapparmor130
          hostPath:
            path: /usr/lib64/libapparmor.so.1.3.0
        - name: libseccomp
          hostPath:
            path: /usr/lib64/libseccomp.so
        - name: libseccomp2
          hostPath:
            path: /usr/lib64/libseccomp.so.2
        - name: libseccomp231
          hostPath:
            path: /usr/lib64/libseccomp.so.2.3.1
