kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datasets
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{SHARED_VOLUME_SIZE}}
  storageClassName: fast
