apiVersion: v1
kind: PersistentVolume
metadata:
  # PersistentVolumes are not namespaced, so you need to have an
  #  identifier in the name
  name: home-{{CLUSTER_IDENTIFIER}}
  # Needed (but dangerous) to keep the notebook from freezing at LDF.
  annotations:
    volume.beta.kubernetes.io/mount-options: "local_lock=all"
spec:
  capacity:
    # Must be a little smaller than the actual PV.
    storage: {{SHARED_VOLUME_SIZE}}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  nfs:
    server: {{NFS_SERVER_IP_ADDRESS}}
    path: "/exports/home"
