apiVersion: v1
kind: PersistentVolume
metadata:
  name: jld-fileserver-home
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  nfs:
    server: jld-fileserver
    path: "/exports/home"
