kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jld-fileserver-physpvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1000Gi
  storageClassName: fast

