apiVersion: v1
kind: PersistentVolume
metadata:
  # PersistentVolumes are not namespaced, so you need to have an
  #  identifier in the name
  name: jld-fileserver-home-demo
  annotations:
    volume.beta.kubernetes.io/mount-options: "local_lock=all"
spec:
  capacity:
    # Must be a little smaller than the actual PV.
    storage: 490Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  nfs:
    #server: jld-fileserver
    # This currently needs to be an IP, so you have to create the
    # service, get the service cluster IP, and use that.
    server: 10.123.249.151
    path: "/exports/home"
