kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{SHARED_VOLUME_SIZE}}
  storageClassName: fast
