apiVersion: v1
kind: Service
metadata:
  name: firefly
  labels:
    name: firefly
spec:
  type: NodePort
  ports:
  - name: tomcat
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: firefly
