apiVersion: v1
kind: Secret
metadata:
  name: jld-hub
data:
  # echo -n $ITEM | base64 -i -
  oauth_client_id: '{{OAUTH_CLIENT_ID}}'
  oauth_secret: '{{OAUTH_SECRET}}'
  oauth_callback_url: '{{OAUTH_CALLBACK_URL}}'
  github_organization_whitelist: '{{GITHUB_ORGANIZATION_WHITELIST}}'
  session_db_url: '{{SESSION_DB_URL}}'
  jupyterhub_crypto_key: '{{JUPYTERHUB_CRYPTO_KEY}}'
