kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{CLUSTER_IDENTIFIER}}
  name: jld-dask
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "create", "delete"]
