kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{CLUSTER_IDENTIFIER}}
  name: jld-hub
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["get", "list", "create", "watch", "delete"]
