kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jld-hub
subjects:
- kind: ServiceAccount
  name: jld-hub
  namespace: {{CLUSTER_IDENTIFIER}}
  apiGroup: ""
roleRef:
  kind: Role
  name: jld-hub
  apiGroup: ""

