apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jld-hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld-hub
    spec:
      serviceAccountName: jld-hub
      containers:
        - name: jld-hub
          imagePullPolicy: "Always"
          image: "lsstsqre/jld-hub"
          resources:
            limits:
              memory: 2G
              cpu: 2.0
            requests:
              memory: 1G
              cpu: 0.8
          ports:
            -
              containerPort: 8000
              name: jld-hub
          env:
            - name: LOGLEVEL
              value: INFO
            - name: LAB_SELECTOR_TITLE
              value: '{{LAB_SELECTOR_TITLE}}'
            # Set to non-empty value to enable debugging.
            - name: DEBUG
              value: '{{DEBUG}}'
            # Set to customize what repo and what images to scan.
            - name: LAB_REPO_HOST
              value: '{{LAB_REPO_HOST}}'
            - name: LAB_REPO_OWNER
              value: '{{LAB_REPO_OWNER}}'
            - name: LAB_REPO_NAME
              value: '{{LAB_REPO_NAME}}'
            # Set if you do not want to scan a repository for images.
            - name: LAB_IMAGE
              value: '{{LAB_IMAGE}}'
            # Set if you want something other than 12 hours.  Setting to
            # zero or a negative value disables.
            - name: LAB_IDLE_TIMEOUT
              value: '{{LAB_IDLE_TIMEOUT}}'
            - name: LAB_MEM_LIMIT
              value: '{{LAB_MEM_LIMIT}}'
            - name: LAB_CPU_LIMIT
              value: '{{LAB_CPU_LIMIT}}'
            - name: LAB_MEM_GUARANTEE
              value: '{{LAB_MEM_GUARANTEE}}'
            - name: LAB_CPU_GUARANTEE
              value: '{{LAB_CPU_GUARANTEE}}'
            - name: JUPYTERLAB_CONFIG_DIR
              value: '/opt/lsst/software/jupyterhub/config'
            - name: GITHUB_ORGANIZATION_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_organization_whitelist
            - name: CILOGON_GROUP_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: cilogon_group_whitelist
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: oauth_client_id
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: oauth_secret
            - name: OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: oauth_callback_url
            # You want this if you're using CILogon rather than GitHub
            #  and not using 'cilogon.org'
            - name: CILOGON_HOST
              value: 'test.cilogon.org'
            # This may contain credentials, so it should be a secret
            - name: SESSION_DB_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: session_db_url
            # This is one or more 32-byte encryption keys (separated
            # with ';') needed to persist auth_state.  They can be
            # base64 or hex-encoded.  Two lets you do key rotation
            - name: JUPYTERHUB_CRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: jupyterhub_crypto_key
          # If you use sqlite, you want this to persist sessions across
          #  jupyterhub restarts.
          volumeMounts:
            - name: jld-hub-home-jupyter
              mountPath: /home/jupyter
            - name: jld-hub-config
              mountPath: /opt/lsst/software/jupyterhub/config
      volumes:
        - name: jld-hub-home-jupyter
          persistentVolumeClaim:
           claimName: jld-hub-physpvc
        - name: jld-hub-config
          configMap:
            name: jld-hub-config
            #  Create with `kubectl create configmap jld-hub-config \
            #   --from-file=config/jupyterhub_config.py \
            #   --from-file=config/jupyterhub_config.d`
            #  It is sort of annoying that you still have to specify
            #   each file in the directory.
            items:
            - key: jupyterhub_config.py
              path: jupyterhub_config.py
            - key: 00-preamble.py
              path: jupyterhub_config.d/00-preamble.py
            - key: 10-authenticator.py
              path: jupyterhub_config.d/10-authenticator.py
            - key: 20-spawner.py
              path: jupyterhub_config.d/20-spawner.py
            - key: 30-environment.py
              path: jupyterhub_config.d/30-environment.py
