kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jld-hub
subjects:
- kind: ServiceAccount
  name: jld-hub
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jld-hub
  apiGroup: rbac.authorization.k8s.io



