apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld
    spec:
      containers:

        - name: jld
          imagePullPolicy: "Always"
          image: "lsstsqre/jld-hub"
          ports:
            -
              containerPort: 8000
              name: jld
          env:
            - name: LOGLEVEL
              value: INFO
            - name: GITHUB_ORGANIZATION_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: jld
                  key: github_organization_whitelist
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jld
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jld
                  key: github_secret
            - name: OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: jld
                  key: github_oauth_callback_url
