apiVersion: v1
kind: Secret
metadata:
  name: jld-hub
data:
  # echo -n $ITEM | base64 -i -
  github_client_id: 'FIXME'
  github_oauth_callback_url: 'FIXME'
  github_organization_whitelist: 'FIXME'
  github_secret: 'FIXME'
  session_db_url: 'FIXME'
  jupyterhub_crypto_key: 'FIXME'
