apiVersion: v1
kind: Secret
metadata:
  name: hub
data:
  # echo -n $ITEM | base64 -i -
  oauth_client_id: '{{OAUTH_CLIENT_ID}}'
  oauth_secret: '{{OAUTH_SECRET}}'
  oauth_callback_url: '{{OAUTH_CALLBACK_URL}}'
  github_organization_whitelist: '{{GITHUB_ORGANIZATION_WHITELIST}}'
  github_organization_denylist: '{{GITHUB_ORGANIZATION_DENYLIST}}'
  cilogon_group_whitelist: '{{CILOGON_GROUP_WHITELIST}}'
  cilogon_group_denylist: '{{CILOGON_GROUP_DENYLIST}}'
  session_db_url: '{{SESSION_DB_URL}}'
  jupyterhub_crypto_key: '{{JUPYTERHUB_CRYPTO_KEY}}'
  configproxy_auth_token: '{{CONFIGPROXY_AUTH_TOKEN}}'

