apiVersion: v1
kind: Service
metadata:
  name: jld
  labels:
    name: jld
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    name: jld
