# Secrets for filebeats
apiVersion: v1
kind: Secret
metadata:
  name: filebeat
data:
  # echo -n ${CA_CERTIFICATE} | base64 -i -
  ca.crt: '{{CA_CERTIFICATE}}'
  beats.crt: '{{BEATS_CERTIFICATE}}'
  beats.key: '{{BEATS_KEY}}'
